name: spotdetec
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy
  - scipy
  - pandas
  - matplotlib
  - pip:
    - tifffile
    - imageio
    - trackpy
    - scikit-image
    - PyQt5
    - pyinstaller
